version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ChangeMe123
    volumes:
      - mongo_data:/data/db

  app:
    build: ./app
    container_name: inventory-app
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://admin:ChangeMe123@mongo:27017/?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo_data:
